name: dbt_run_streamline_history_temp
run-name: dbt_run_streamline_history_temp

on:
  workflow_dispatch:
  schedule:
    - cron: '24 */2 * * *'

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run History Models
      command: |
        dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True, "MAIN_SL_CONFIRM_BLOCKS_HISTORY_SQL_LIMIT":800000}' -m "fsc_evm,tag:streamline,tag:core,tag:complete,tag:confirm_blocks" "fsc_evm,tag:streamline,tag:core,tag:history,tag:confirm_blocks"
    secrets: inherit